### ISSUE TITLE
Not working, poor documentation 

### ISSUE THREAD

**Issue by R0N1n-dev** [samzhangjy/VueBlogger#5]
Followed documentation.
Gives error of can't find several files. 
The documentation is really poor and unclear.

**Comment by samzhangjy** [comment]
Hi. Can you please copy paste the error messages? This will help to fix this issue.

**Comment by bullshitking-99** [comment]
## I met the same problem which can't run locally. 
here are my steps:
- git clone 
- yarn 
- yarn serve 
> This dependency was not found:
> *@/../posts in ./src/router/index.js
> To install it, you can run: npm install --save @/../posts

then i read docs again and find that i need to add the "posts/data/posts.json"
finally success after this, just tell others how to fix this problem

> Followed documentation. Gives error of can't find several files. The documentation is really poor and unclear.

## project is awsome , thank you for the author 😊
